name: test-action
inputs:
  some-arg:
    required: true
    default: 'arg-value'
outputs:
  time:
    description: 'time info'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.some-arg }}